### ISSUE TITLE
> trigger doesnt work due to markdown

### ISSUE THREAD

**Issue by OfficiallySp** [auyer/commanderBot#31]
using the > followed by a space autoconverts into a blockquote as discord supports markdown
see example below
![image](https://user-images.githubusercontent.com/46799448/108927826-faa07d00-7638-11eb-96e4-0ec560642e71.png)

**Comment by auyer** [comment]
This only happens if you include a space after it!

![image](https://user-images.githubusercontent.com/12375421/109070308-18212580-76d1-11eb-887a-942641309399.png)

**Comment by auyer** [comment]
Our hosted version of the bot is unavailable at the moment because of some issues caused by discord's permissions. I'm still waiting on their support to reply to my tickets. In the meantime, you can host your own instance of the bot!

**Comment by OfficiallySp** [comment]
thank you. i was confused when the documentation shows a space inbetween the command. thanks for the heads up
