### ISSUE TITLE
Summon command

### ISSUE THREAD

**Issue by auyer** [auyer/commanderBot#8]
The summon command should be capable of moving players from a variety of channels to a chosen channel.

Proposed command structures:
Proposal 1:

- `> summon`       (help message)
- `> summon all`                 (every non afk)
- `> summon all afk`          (all, including AFK )
- `> summon destination`   (every non afk)

Proposal 2:

- `> summon`       (help message)
- `> summon destination`       (every non afk)
- `> summon here`                  (every non afk)
- `> summon all here`            (all, including AFK )
- `> summon all destination`   (all, including AFK )

**Comment by Jabulba** [comment]
maybe something like

summon all
summon all [+afk]
summon <channel_name>
summon <channel_name> [+afk]
summon <channel_number>
summon <channel_number> [+afk]

**Comment by auyer** [comment]
Resolved by #9
